# Generated by Django 5.2.3 on 2025-07-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="subtitle",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
